[xamarin] fix for DebugConfig and read-only file system
Using `DebugInProcessConfig` results in an error on Android:

    System.IO.IOException: Read-only file system
        at System.IO.FileSystem.CreateDirectory (System.String fullPath) [0x00187] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs:317
        at System.IO.Directory.CreateDirectory (System.String path) [0x0002c] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.IO.FileSystem/src/System/IO/Directory.cs:40
        at BenchmarkDotNet.Extensions.CommonExtensions.CreateIfNotExists (System.String directoryPath) [0x0000e] in C:\src\BenchmarkDotNet\src\BenchmarkDotNet\Extensions\CommonExtensions.cs:71
        at BenchmarkDotNet.Running.BenchmarkRunnerClean.GetRootArtifactsFolderPath (BenchmarkDotNet.Running.BenchmarkRunInfo[] benchmarkRunInfos) [0x00058] in C:\src\BenchmarkDotNet\src\BenchmarkDotNet\Running\BenchmarkRunnerClean.cs:534
        at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run (BenchmarkDotNet.Running.BenchmarkRunInfo[] benchmarkRunInfos) [0x00014] in C:\src\BenchmarkDotNet\src\BenchmarkDotNet\Running\BenchmarkRunnerClean.cs:40
        at BenchmarkDotNet.Running.BenchmarkRunner.RunWithDirtyAssemblyResolveHelper (System.Type type, BenchmarkDotNet.Configs.IConfig config) [0x00000] in C:\src\BenchmarkDotNet\src\BenchmarkDotNet\Running\BenchmarkRunnerDirty.cs:77
        at BenchmarkDotNet.Running.BenchmarkRunner+<>c__DisplayClass0_0`1[T].<Run>b__0 () [0x00000] in C:\src\BenchmarkDotNet\src\BenchmarkDotNet\Running\BenchmarkRunnerDirty.cs:23
        at BenchmarkDotNet.Running.BenchmarkRunner.RunWithExceptionHandling (System.Func`1[TResult] run) [0x00002] in C:\src\BenchmarkDotNet\src\BenchmarkDotNet\Running\BenchmarkRunnerDirty.cs:107
        at BenchmarkDotNet.Running.BenchmarkRunner.Run[T] (BenchmarkDotNet.Configs.IConfig config) [0x00014] in C:\src\BenchmarkDotNet\src\BenchmarkDotNet\Running\BenchmarkRunnerDirty.cs:23
        at BenchmarkDotNet.Samples.Forms.MainPage+<>c__DisplayClass1_0.<Button_Clicked>b__0 () [0x0000f] in C:\src\BenchmarkDotNet\samples\BenchmarkDotNet.Samples.Forms\MainPage.xaml.cs:32
        at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2476
        at System.Threading.Tasks.Task.Execute () [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2319
        --- End of stack trace from previous location where exception was thrown ---
        at BenchmarkDotNet.Samples.Forms.MainPage.Button_Clicked (System.Object sender, System.EventArgs e) [0x00077] in C:\src\BenchmarkDotNet\samples\BenchmarkDotNet.Samples.Forms\MainPage.xaml.cs:26

In 9c0f5239, I fixed `DefaultConfig.ArtifactPath`'s usage of
`Directory.GetCurrentDirectory()` so that `ArtifactPath` defaults to a
writeable directory on Android.

We need the same fix in `DebugConfig.ArtifactPath`, but I also added
`RuntimeInformation.IsAndroid()` and `RuntimeInformation.IsiOS()` to
make things a bit better.

I updated the Xamarin sample to use a `DebugInProcessConfig` for
`Debug` configurations.