[wasm] Set the $RUNTIMESRCDIR$ for interpreter
Fixes:

    The "WasmAppBuilder" task failed unexpectedly.
    System.ArgumentException: File MainJS='$RUNTIMESRCDIR$\src\mono\wasm\runtime-test.js' doesn't exist.
       at WasmAppBuilder.Execute() in WasmAppBuilder.dll:token 0x6000042+0x27
       at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() in Microsoft.Build.dll:token 0x6001602+0x3e
       at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) in Microsoft.Build.dll:token 0x6001481+0x2b5